### ISSUE TITLE
Lat/lon variables can be in root group

### ISSUE THREAD

**Issue by nlenssen2013** [podaac/l2ss-py-autotest#1365]
Current code assumes all the variables are in the last group of the file. SNDR has lat/lon variables at the same level as some groups and gets missed. First check for lat/lon variables should be in the root group before checking the groups in line. This fixes SNDR ACOS and OCO3.

**Comment by jamesfwood** [comment]
Hi @nlenssen2013 
Is this one still an issue?  If not, can you close it?
Thanks!
