### ISSUE TITLE
Get l2ss-py-autotest PRs to show shortname in the title properly

### ISSUE THREAD

**Issue by jamesfwood** [podaac/l2ss-py-autotest#1815]
The shortname shows up in some collections, but others it's just showing ()

Please make sure it fills in the short name properly. 

Clear all the PRs until they show the short name properly.

**Comment by jonathansmolenski** [comment]
This has been completed.  There was a command that queries json fields from the metadata file that worked strangely in shell commands and needed to be encapsulated in single quotes.
