### ISSUE TITLE
Add more nightly jobs to l2ss-py-autotest

### ISSUE THREAD

**Issue by jamesfwood** [podaac/l2ss-py-autotest#1819]
Includes these issues:

- https://github.com/podaac/l2ss-py-autotest/issues/1816
- https://github.com/podaac/l2ss-py-autotest/issues/1817
- https://github.com/podaac/l2ss-py-autotest/issues/1918

**Comment by jonathansmolenski** [comment]
https://github.com/podaac/l2ss-py-autotest/issues/1918 as well
